### PR TITLE
Just a codeowner manually signing license

### PR DESCRIPTION
**Pull request by bumblefudge**
testing testing 1 2 3

### CODE REVIEW

**Review by oed — COMMENTED** [review]
So every contributor need to add their own name in this way? Can it be an anon?

**Comment by bumblefudge** [comment]
Not sure-- I'll wait for @expede to explain here for fear of misinforming off the top of my misinformed head.  

I manually added us three CODEOWNERS [here](https://github.com/ChainAgnostic/varsig/commit/87cf3b38a4b953bf86a73cf6c2e72e7a3e487429) for the sake of experimentation, gonna try to re-check now

**Comment by bumblefudge** [comment]
RecheckCLAplz

**Comment by bumblefudge** [comment]
@cla-bot check

**Comment by bumblefudge** [comment]
OK seems that we can "accept" their PR by adding them to the config file, not sure about how to handle anons.  Personally, I'd say the individual contributor controlling the github account doesn't need to be doxxed qua natural person if they have signatory authority to waive IP/patent claims on behalf of some legal person that can show up in court, but I defer to others with more Community Spec experience than I on where the boundary of legal accountability should be drawn.

**Comment by expede** [comment]
Thanks for signing @bumblefudge 🎉 

> So every contributor need to add their own name in this way? 

Yes. It needs to be traceable back to the committer.

> Can it be an anon?

Anonymous? It cannot be anonymous because you're signing a legal agreement to release the intellectual property into the community ("I agree to not sue anyone who builds on top of these ideas"). This is more lightweight than the IETF and W3C, but the same basic idea. Blaine showed me the one that they did for OAuth 1 back in the day, and it's similar in content.

**Comment by expede** [comment]
Ah I see that @oed ended up in the `.clabot` file. If you could make a PR that looks like the Notices here, that would be helpful (or we can remove you from the `.clabot` — up to you!)

It's definitely inconvenient to have to do this, but it's WAY less inconvenient than doing it after the fact and having to hunt people down.

**Review by expede — APPROVED** [review]
🎉 🙏

**Comment by oed** [comment]
> Anonymous? It cannot be anonymous because you're signing a legal agreement to release the intellectual property into the community ("I agree to not sue anyone who builds on top of these ideas"). This is more lightweight than the IETF and W3C, but the same basic idea. Blaine showed me the one that they did for OAuth 1 back in the day, and it's similar in content.

I guess by anon I mean pseudonymous, e.g. can a random github account who we don't know who it is contribute?

**Pull request merged**
